export type SupportedMIMEType =
  | "text/plain" // .txt
  | "text/csv" // .csv
  | "text/html" // .html、.htm
  | "text/javascript" // .js、.mjs
  | "text/css" // .css
  | "application/javascript" // .js
  | "application/json" // .json
  | "application/pdf" // .pdf
  | "application/vnd.ms-excel" // .xls
  | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" // .xlsx
  | "application/vnd.openxmlformats-officedocument.wordprocessingml.document" // .docx
  | "application/vnd.ms-word" // .doc
  | "image/jpeg" // .jpg、.jpeg
  | "image/png" // .png
  | "image/svg+xml" // .svg
  | "image/webp" // .webp
  | "image/gif" // .gif
  | "audio/mpeg" // .mp3
  | "video/mp4" // .mp4
  | "video/x-msvideo"; // .avi
