# Generated by Django 4.2.16 on 2025-03-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkflowDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="流程图ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="( 100 字符以内 )",
                        max_length=100,
                        verbose_name="流程图名称",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="( 250 字符以内 )",
                        max_length=250,
                        verbose_name="流程图简介",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LOGIC", "LOGIC ( 逻辑图 )"),
                            ("DRAFT", "DRAFT ( 草稿图 )"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="流程图类型",
                    ),
                ),
                (
                    "element",
                    models.TextField(
                        blank=True,
                        default='{"nodes": [], "edges": [], "variables": []}',
                        help_text="( JSON 格式, 必须包含 nodes、edges、variables )",
                        verbose_name="流程图元素",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="启动中"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建日期"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日期"),
                ),
            ],
            options={
                "verbose_name_plural": "Workflow Data",
                "db_table": "workflow_data",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowHistoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="履历ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="( 100 字符以内 )",
                        max_length=100,
                        verbose_name="履历名称",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="( 250 字符以内 )",
                        max_length=250,
                        verbose_name="履历简介",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建日期"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日期"),
                ),
            ],
            options={
                "verbose_name_plural": "Workflow History",
                "db_table": "workflow_history",
                "ordering": ["id"],
            },
        ),
    ]
